# Generated by Django 4.1.4 on 2022-12-07 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainCategory', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('mapping', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mapping', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Color',
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('originalPrice', models.IntegerField()),
                ('sellingPrice', models.IntegerField()),
                ('reviewCount', models.IntegerField(default=0)),
                ('starRate', models.IntegerField(default=0)),
                ('thumbnailUrl', models.CharField(max_length=200)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closet.category')),
                ('colorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closet.color')),
            ],
            options={
                'verbose_name_plural': 'Clothes',
            },
        ),
    ]
